version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    links:
      - pg_db

  pg_db:
    image: postgres
    environment:
      - PGPORT=5433
      - PGUSERNAME=postgres
      - PGPASSWORD=test
      - PGDATABASE=DevDB

